// Code generated by protoc-gen-go.
// source: foamcoin.proto
// DO NOT EDIT!

/*
Package coin is a generated protocol buffer package.

It is generated from these files:
	foamcoin.proto

It has these top-level messages:
	Account
	AccountSlice
	TxoutMap
	TX
	ExecResult
	QueryAddrResults
	HydruscoinInfo
	Test
	Incentive
*/
package coin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// account model digitalAssets
type Account struct {
	Addr    string               `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Balance int64                `protobuf:"varint,2,opt,name=balance" json:"balance,omitempty"`
	Txouts  map[string]*TX_TXOUT `protobuf:"bytes,3,rep,name=txouts" json:"txouts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetTxouts() map[string]*TX_TXOUT {
	if m != nil {
		return m.Txouts
	}
	return nil
}

type AccountSlice struct {
	Addr     string      `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Balance  int64       `protobuf:"varint,2,opt,name=balance" json:"balance,omitempty"`
	Txoutmap []*TxoutMap `protobuf:"bytes,3,rep,name=txoutmap" json:"txoutmap,omitempty"`
}

func (m *AccountSlice) Reset()                    { *m = AccountSlice{} }
func (m *AccountSlice) String() string            { return proto.CompactTextString(m) }
func (*AccountSlice) ProtoMessage()               {}
func (*AccountSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountSlice) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *AccountSlice) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *AccountSlice) GetTxoutmap() []*TxoutMap {
	if m != nil {
		return m.Txoutmap
	}
	return nil
}

type TxoutMap struct {
	Key    string    `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Txouts *TX_TXOUT `protobuf:"bytes,2,opt,name=txouts" json:"txouts,omitempty"`
}

func (m *TxoutMap) Reset()                    { *m = TxoutMap{} }
func (m *TxoutMap) String() string            { return proto.CompactTextString(m) }
func (*TxoutMap) ProtoMessage()               {}
func (*TxoutMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TxoutMap) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TxoutMap) GetTxouts() *TX_TXOUT {
	if m != nil {
		return m.Txouts
	}
	return nil
}

// utxo tx
type TX struct {
	Version   uint64      `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Timestamp int64       `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Txin      []*TX_TXIN  `protobuf:"bytes,3,rep,name=txin" json:"txin,omitempty"`
	Txout     []*TX_TXOUT `protobuf:"bytes,4,rep,name=txout" json:"txout,omitempty"`
	Founder   string      `protobuf:"bytes,5,opt,name=founder" json:"founder,omitempty"`
}

func (m *TX) Reset()                    { *m = TX{} }
func (m *TX) String() string            { return proto.CompactTextString(m) }
func (*TX) ProtoMessage()               {}
func (*TX) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TX) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TX) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TX) GetTxin() []*TX_TXIN {
	if m != nil {
		return m.Txin
	}
	return nil
}

func (m *TX) GetTxout() []*TX_TXOUT {
	if m != nil {
		return m.Txout
	}
	return nil
}

func (m *TX) GetFounder() string {
	if m != nil {
		return m.Founder
	}
	return ""
}

// txin not specified who has this txin, because creator can use their txout only, txin must be creator's previous txout
type TX_TXIN struct {
	Ix         uint32 `protobuf:"varint,1,opt,name=ix" json:"ix,omitempty"`
	SourceHash string `protobuf:"bytes,2,opt,name=sourceHash" json:"sourceHash,omitempty"`
	// indicate owner's addr
	Addr      string `protobuf:"bytes,3,opt,name=addr" json:"addr,omitempty"`
	Script    string `protobuf:"bytes,4,opt,name=script" json:"script,omitempty"`
	Undefined string `protobuf:"bytes,5,opt,name=undefined" json:"undefined,omitempty"`
}

func (m *TX_TXIN) Reset()                    { *m = TX_TXIN{} }
func (m *TX_TXIN) String() string            { return proto.CompactTextString(m) }
func (*TX_TXIN) ProtoMessage()               {}
func (*TX_TXIN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *TX_TXIN) GetIx() uint32 {
	if m != nil {
		return m.Ix
	}
	return 0
}

func (m *TX_TXIN) GetSourceHash() string {
	if m != nil {
		return m.SourceHash
	}
	return ""
}

func (m *TX_TXIN) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *TX_TXIN) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *TX_TXIN) GetUndefined() string {
	if m != nil {
		return m.Undefined
	}
	return ""
}

type TX_TXOUT struct {
	Value        int64  `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Addr         string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Until        int64  `protobuf:"varint,3,opt,name=until" json:"until,omitempty"`
	ScriptPubKey string `protobuf:"bytes,4,opt,name=scriptPubKey" json:"scriptPubKey,omitempty"`
	Undefined    string `protobuf:"bytes,5,opt,name=undefined" json:"undefined,omitempty"`
}

func (m *TX_TXOUT) Reset()                    { *m = TX_TXOUT{} }
func (m *TX_TXOUT) String() string            { return proto.CompactTextString(m) }
func (*TX_TXOUT) ProtoMessage()               {}
func (*TX_TXOUT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 1} }

func (m *TX_TXOUT) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TX_TXOUT) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *TX_TXOUT) GetUntil() int64 {
	if m != nil {
		return m.Until
	}
	return 0
}

func (m *TX_TXOUT) GetScriptPubKey() string {
	if m != nil {
		return m.ScriptPubKey
	}
	return ""
}

func (m *TX_TXOUT) GetUndefined() string {
	if m != nil {
		return m.Undefined
	}
	return ""
}

// ExecResult is the result of processing a transaction
type ExecResult struct {
	SumCurrentOutputs int64 `protobuf:"varint,1,opt,name=sumCurrentOutputs" json:"sumCurrentOutputs,omitempty"`
	SumPriorOutputs   int64 `protobuf:"varint,2,opt,name=sumPriorOutputs" json:"sumPriorOutputs,omitempty"`
}

func (m *ExecResult) Reset()                    { *m = ExecResult{} }
func (m *ExecResult) String() string            { return proto.CompactTextString(m) }
func (*ExecResult) ProtoMessage()               {}
func (*ExecResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExecResult) GetSumCurrentOutputs() int64 {
	if m != nil {
		return m.SumCurrentOutputs
	}
	return 0
}

func (m *ExecResult) GetSumPriorOutputs() int64 {
	if m != nil {
		return m.SumPriorOutputs
	}
	return 0
}

// QueryAddrResults returns the result of query function query_addr
type QueryAddrResults struct {
	Accounts map[string]*Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *QueryAddrResults) Reset()                    { *m = QueryAddrResults{} }
func (m *QueryAddrResults) String() string            { return proto.CompactTextString(m) }
func (*QueryAddrResults) ProtoMessage()               {}
func (*QueryAddrResults) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueryAddrResults) GetAccounts() map[string]*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// HydruscoinInfo
type HydruscoinInfo struct {
	CoinTotal    int64                      `protobuf:"varint,1,opt,name=coinTotal" json:"coinTotal,omitempty"`
	AccountTotal int64                      `protobuf:"varint,2,opt,name=accountTotal" json:"accountTotal,omitempty"`
	TxoutTotal   int64                      `protobuf:"varint,3,opt,name=txoutTotal" json:"txoutTotal,omitempty"`
	TxTotal      int64                      `protobuf:"varint,4,opt,name=txTotal" json:"txTotal,omitempty"`
	Session      *HydruscoinInfo_POVSession `protobuf:"bytes,5,opt,name=session" json:"session,omitempty"`
	// when you init, you put other valiables into 0, so message bytes will be nil, can't be put into states
	Placeholder string `protobuf:"bytes,6,opt,name=placeholder" json:"placeholder,omitempty"`
}

func (m *HydruscoinInfo) Reset()                    { *m = HydruscoinInfo{} }
func (m *HydruscoinInfo) String() string            { return proto.CompactTextString(m) }
func (*HydruscoinInfo) ProtoMessage()               {}
func (*HydruscoinInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *HydruscoinInfo) GetCoinTotal() int64 {
	if m != nil {
		return m.CoinTotal
	}
	return 0
}

func (m *HydruscoinInfo) GetAccountTotal() int64 {
	if m != nil {
		return m.AccountTotal
	}
	return 0
}

func (m *HydruscoinInfo) GetTxoutTotal() int64 {
	if m != nil {
		return m.TxoutTotal
	}
	return 0
}

func (m *HydruscoinInfo) GetTxTotal() int64 {
	if m != nil {
		return m.TxTotal
	}
	return 0
}

func (m *HydruscoinInfo) GetSession() *HydruscoinInfo_POVSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *HydruscoinInfo) GetPlaceholder() string {
	if m != nil {
		return m.Placeholder
	}
	return ""
}

type HydruscoinInfo_POVSession struct {
	TxCount               int64 `protobuf:"varint,1,opt,name=txCount" json:"txCount,omitempty"`
	Threshold             int64 `protobuf:"varint,2,opt,name=threshold" json:"threshold,omitempty"`
	CurrentTotalIncentive int64 `protobuf:"varint,3,opt,name=currentTotalIncentive" json:"currentTotalIncentive,omitempty"`
	CurrentAlpha          int64 `protobuf:"varint,4,opt,name=currentAlpha" json:"currentAlpha,omitempty"`
}

func (m *HydruscoinInfo_POVSession) Reset()                    { *m = HydruscoinInfo_POVSession{} }
func (m *HydruscoinInfo_POVSession) String() string            { return proto.CompactTextString(m) }
func (*HydruscoinInfo_POVSession) ProtoMessage()               {}
func (*HydruscoinInfo_POVSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *HydruscoinInfo_POVSession) GetTxCount() int64 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *HydruscoinInfo_POVSession) GetThreshold() int64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *HydruscoinInfo_POVSession) GetCurrentTotalIncentive() int64 {
	if m != nil {
		return m.CurrentTotalIncentive
	}
	return 0
}

func (m *HydruscoinInfo_POVSession) GetCurrentAlpha() int64 {
	if m != nil {
		return m.CurrentAlpha
	}
	return 0
}

type Test struct {
	INCENT_T0          int64 `protobuf:"varint,1,opt,name=INCENT_T0,json=iNCENTT0" json:"INCENT_T0,omitempty"`
	INCENT_ALPHA0      int64 `protobuf:"varint,2,opt,name=INCENT_ALPHA0,json=iNCENTALPHA0" json:"INCENT_ALPHA0,omitempty"`
	INCENT_THREADSHOLD int64 `protobuf:"varint,3,opt,name=INCENT_THREADSHOLD,json=iNCENTTHREADSHOLD" json:"INCENT_THREADSHOLD,omitempty"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Test) GetINCENT_T0() int64 {
	if m != nil {
		return m.INCENT_T0
	}
	return 0
}

func (m *Test) GetINCENT_ALPHA0() int64 {
	if m != nil {
		return m.INCENT_ALPHA0
	}
	return 0
}

func (m *Test) GetINCENT_THREADSHOLD() int64 {
	if m != nil {
		return m.INCENT_THREADSHOLD
	}
	return 0
}

type Incentive struct {
	Tx []*TX   `protobuf:"bytes,1,rep,name=tx" json:"tx,omitempty"`
	Id []int64 `protobuf:"varint,2,rep,packed,name=id" json:"id,omitempty"`
}

func (m *Incentive) Reset()                    { *m = Incentive{} }
func (m *Incentive) String() string            { return proto.CompactTextString(m) }
func (*Incentive) ProtoMessage()               {}
func (*Incentive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Incentive) GetTx() []*TX {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *Incentive) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "coin.Account")
	proto.RegisterType((*AccountSlice)(nil), "coin.AccountSlice")
	proto.RegisterType((*TxoutMap)(nil), "coin.TxoutMap")
	proto.RegisterType((*TX)(nil), "coin.TX")
	proto.RegisterType((*TX_TXIN)(nil), "coin.TX.TXIN")
	proto.RegisterType((*TX_TXOUT)(nil), "coin.TX.TXOUT")
	proto.RegisterType((*ExecResult)(nil), "coin.ExecResult")
	proto.RegisterType((*QueryAddrResults)(nil), "coin.QueryAddrResults")
	proto.RegisterType((*HydruscoinInfo)(nil), "coin.HydruscoinInfo")
	proto.RegisterType((*HydruscoinInfo_POVSession)(nil), "coin.HydruscoinInfo.POVSession")
	proto.RegisterType((*Test)(nil), "coin.Test")
	proto.RegisterType((*Incentive)(nil), "coin.Incentive")
}

func init() { proto.RegisterFile("foamcoin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x95, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0xe5, 0x97, 0xa4, 0xc9, 0xa4, 0xc9, 0xd3, 0xae, 0xfa, 0xa0, 0x10, 0x10, 0x04, 0xb7,
	0x42, 0x11, 0x82, 0xa8, 0x14, 0x90, 0x80, 0x13, 0x51, 0x1b, 0x29, 0x81, 0xd2, 0x04, 0xd7, 0xa0,
	0xde, 0x90, 0x6b, 0x6f, 0x14, 0x0b, 0xc7, 0xb6, 0x76, 0xd7, 0xc5, 0xb9, 0x71, 0x85, 0x0f, 0x81,
	0xf8, 0x04, 0xdc, 0xf8, 0x7e, 0x68, 0x5f, 0x9c, 0xd8, 0x25, 0x42, 0xe2, 0xb6, 0xf3, 0x9f, 0xf1,
	0xce, 0x6f, 0x66, 0x67, 0x12, 0x68, 0xcd, 0x62, 0x77, 0xe1, 0xc5, 0x41, 0xd4, 0x4f, 0x48, 0xcc,
	0x62, 0x64, 0xf2, 0xb3, 0xf5, 0x4b, 0x83, 0xad, 0x81, 0xe7, 0xc5, 0x69, 0xc4, 0x10, 0x02, 0xd3,
	0xf5, 0x7d, 0xd2, 0xd6, 0xba, 0x5a, 0xaf, 0x6e, 0x8b, 0x33, 0x6a, 0xc3, 0xd6, 0xa5, 0x1b, 0xba,
	0x91, 0x87, 0xdb, 0x7a, 0x57, 0xeb, 0x19, 0x76, 0x6e, 0xa2, 0xc7, 0x50, 0x65, 0x59, 0x9c, 0x32,
	0xda, 0x36, 0xba, 0x46, 0xaf, 0x71, 0x74, 0xb3, 0x2f, 0x2e, 0x57, 0x97, 0xf5, 0x1d, 0xe1, 0x1b,
	0x46, 0x8c, 0x2c, 0x6d, 0x15, 0xd8, 0x19, 0x43, 0xa3, 0x20, 0xa3, 0x1d, 0x30, 0x3e, 0xe1, 0xa5,
	0x4a, 0xc7, 0x8f, 0xe8, 0x00, 0x2a, 0x57, 0x6e, 0x98, 0xca, 0x5c, 0x8d, 0xa3, 0x96, 0xbc, 0xd2,
	0xb9, 0xe8, 0x3b, 0x17, 0x93, 0xf7, 0x8e, 0x2d, 0x9d, 0x2f, 0xf5, 0xe7, 0x9a, 0x35, 0x87, 0x6d,
	0x95, 0xe9, 0x3c, 0x0c, 0x3c, 0xfc, 0x8f, 0xec, 0x0f, 0xa0, 0x26, 0x90, 0x16, 0x6e, 0xa2, 0xe8,
	0xf3, 0x54, 0x5c, 0x7d, 0xeb, 0x26, 0xf6, 0xca, 0x6f, 0x9d, 0x40, 0x2d, 0x57, 0x37, 0x10, 0xdf,
	0x5f, 0x75, 0x61, 0x33, 0xb2, 0xf2, 0x5a, 0x3f, 0x0d, 0xd0, 0x9d, 0x0b, 0x8e, 0x74, 0x85, 0x09,
	0x0d, 0xe2, 0x48, 0x5c, 0x62, 0xda, 0xb9, 0x89, 0x6e, 0x43, 0x9d, 0x05, 0x0b, 0x4c, 0x99, 0xbb,
	0x48, 0x14, 0xee, 0x5a, 0x40, 0xf7, 0xc0, 0x64, 0x59, 0x10, 0x29, 0xd8, 0x66, 0x21, 0xc9, 0xf8,
	0xcc, 0x16, 0x2e, 0xde, 0x3b, 0x91, 0xab, 0x6d, 0x96, 0x0a, 0x5a, 0xf5, 0x4e, 0x38, 0x39, 0xc0,
	0x2c, 0x4e, 0x23, 0x1f, 0x93, 0x76, 0x45, 0x54, 0x91, 0x9b, 0x9d, 0x2f, 0x1a, 0x98, 0xfc, 0x3a,
	0xd4, 0x02, 0x3d, 0xc8, 0x04, 0x5e, 0xd3, 0xd6, 0x83, 0x0c, 0xdd, 0x01, 0xa0, 0x71, 0x4a, 0x3c,
	0x3c, 0x72, 0xe9, 0x5c, 0xa0, 0xd5, 0xed, 0x82, 0xb2, 0x6a, 0xbd, 0x51, 0x68, 0xfd, 0x0d, 0xa8,
	0x52, 0x8f, 0x04, 0x09, 0xa7, 0xe1, 0xaa, 0xb2, 0x78, 0x95, 0x3c, 0xdb, 0x2c, 0x88, 0xb0, 0xaf,
	0x00, 0xd6, 0x42, 0xe7, 0xab, 0x06, 0x15, 0x41, 0x8b, 0xf6, 0xf2, 0x41, 0xd0, 0x44, 0x27, 0xa4,
	0xb1, 0xca, 0xa4, 0x17, 0x32, 0xed, 0x41, 0x25, 0x8d, 0x58, 0x10, 0x8a, 0xf4, 0x86, 0x2d, 0x0d,
	0x64, 0xc1, 0xb6, 0xcc, 0x38, 0x4d, 0x2f, 0xdf, 0xe0, 0xa5, 0xa2, 0x28, 0x69, 0x7f, 0x67, 0xb1,
	0x7c, 0x80, 0x61, 0x86, 0x3d, 0x1b, 0xd3, 0x34, 0x64, 0xe8, 0x21, 0xec, 0xd2, 0x74, 0x71, 0x9c,
	0x12, 0x82, 0x23, 0x36, 0x49, 0x59, 0xc2, 0x5f, 0x5c, 0xb2, 0xfd, 0xe9, 0x40, 0x3d, 0xf8, 0x8f,
	0xa6, 0x8b, 0x29, 0x09, 0x62, 0x92, 0xc7, 0xca, 0x17, 0xbd, 0x2e, 0x5b, 0x3f, 0x34, 0xd8, 0x79,
	0x97, 0x62, 0xb2, 0x1c, 0xf8, 0x3e, 0x91, 0xb9, 0x28, 0x7a, 0x05, 0x35, 0x57, 0xce, 0x36, 0xcf,
	0xc1, 0x1f, 0xf3, 0x40, 0x3e, 0xe6, 0xf5, 0xc8, 0x7c, 0xd9, 0xd4, 0x9a, 0xad, 0xbe, 0xea, 0xbc,
	0x86, 0x66, 0xc9, 0xb5, 0x61, 0x70, 0xf7, 0xcb, 0xab, 0xd6, 0x2c, 0x6d, 0x6f, 0x71, 0xd3, 0xbe,
	0x19, 0xd0, 0x1a, 0x2d, 0x7d, 0x92, 0x52, 0x1e, 0x31, 0x8e, 0x66, 0x31, 0xef, 0x1c, 0x3f, 0x3b,
	0x31, 0x73, 0x43, 0xd5, 0x85, 0xb5, 0xc0, 0x7b, 0xaf, 0x40, 0x64, 0x80, 0x2c, 0xbd, 0xa4, 0xf1,
	0x99, 0x12, 0xf3, 0x28, 0x23, 0xe4, 0xd3, 0x15, 0x14, 0x3e, 0xa6, 0x2c, 0x93, 0x4e, 0x53, 0xae,
	0xae, 0x32, 0xd1, 0x0b, 0xd8, 0xa2, 0x98, 0x8a, 0x0d, 0xaa, 0x08, 0xf2, 0xbb, 0x92, 0xbc, 0x8c,
	0xd8, 0x9f, 0x4e, 0x3e, 0x9c, 0xcb, 0x30, 0x3b, 0x8f, 0x47, 0x5d, 0x68, 0x24, 0xa1, 0xeb, 0xe1,
	0x79, 0x1c, 0xf2, 0xf9, 0xaf, 0x8a, 0x66, 0x14, 0xa5, 0xce, 0x77, 0x0d, 0x60, 0xfd, 0xa5, 0xa4,
	0x38, 0xe6, 0xd4, 0xaa, 0xca, 0xdc, 0x14, 0xdb, 0x3a, 0x27, 0x98, 0xf2, 0xef, 0x56, 0xdb, 0x9a,
	0x0b, 0xe8, 0x29, 0xfc, 0xef, 0xc9, 0x89, 0x10, 0xcc, 0xe3, 0xc8, 0xc3, 0x11, 0x0b, 0xae, 0xb0,
	0x2a, 0x74, 0xb3, 0x93, 0xf7, 0x4d, 0x39, 0x06, 0x61, 0x32, 0x77, 0x55, 0xe1, 0x25, 0xcd, 0xfa,
	0x0c, 0xa6, 0x83, 0x29, 0x43, 0xb7, 0xa0, 0x3e, 0x3e, 0x3b, 0x1e, 0x9e, 0x39, 0x1f, 0x9d, 0x43,
	0xc5, 0x56, 0x0b, 0x84, 0xe0, 0x1c, 0xa2, 0x7d, 0x68, 0x2a, 0xe7, 0xe0, 0x74, 0x3a, 0x1a, 0x1c,
	0xe6, 0x2f, 0x20, 0x03, 0xa4, 0x86, 0x1e, 0x01, 0xca, 0x6f, 0x18, 0xd9, 0xc3, 0xc1, 0xc9, 0xf9,
	0x68, 0x72, 0x7a, 0xa2, 0x00, 0x77, 0xd5, 0x55, 0x6b, 0x87, 0xf5, 0x0c, 0xea, 0x6b, 0xd2, 0x36,
	0xe8, 0x2c, 0x53, 0xa3, 0x59, 0xcb, 0x7f, 0x67, 0x6c, 0x9d, 0x65, 0xe2, 0xb7, 0x83, 0x37, 0xc4,
	0xe8, 0x19, 0xb6, 0x1e, 0xf8, 0x97, 0x55, 0xf1, 0x5f, 0xf3, 0xe4, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4d, 0x64, 0x0c, 0x5c, 0x7d, 0x06, 0x00, 0x00,
}
